//*************************************
//  Udhay: Audio PLayback
 //*************************************/
const songsByMood = {
  workout: [
    { title: "Stronger – Kanye West", file: "mp3/mp3/stronger.mp3" },
    { title: "Eye of the Tiger – Survivor", file: "mp3/mp3/eye_of_the_tiger.mp3" },
    { title: "Lose Yourself – Eminem", file: "mp3/mp3/lose_yourself.mp3" },
    { title: "Uptown Funk – Bruno Mars", file: "mp3/mp3/uptown_funk.mp3" },
    { title: "Cant Hold Us – Macklemore & Ryan Lewis", file: "mp3/mp3/cant_hold_us.mp3" },
    { title: "Turn Down for What – DJ Snake & Lil Jon", file: "mp3/mp3/turn_down_for_what.mp3" },
    { title: "POWER – Kanye West", file: "mp3/mp3/power.mp3" },
    { title: "Titanium – David Guetta ft. Sia", file: "mp3/mp3/titanium.mp3" },
    { title: "Till I Collapse – Eminem", file: "mp3/mp3/till_i_collapse.mp3" },
    { title: "Remember the Name – Fort Minor", file: "mp3/mp3/remember_the_name.mp3" },
    { title: "Dont Start Now – Dua Lipa", file: "mp3/mp3/dont_start_now.mp3" },
    { title: "Levitating – Dua Lipa", file: "mp3/mp3/levitating.mp3" },
    { title: "Pepas – Farruko", file: "mp3/mp3/pepas.mp3" },
    { title: "Blinding Lights – The Weeknd", file: "mp3/mp3/blinding_lights.mp3" },
    { title: "Heat Waves – Glass Animals", file: "mp3/mp3/heat_waves.mp3" }
  ],
  driving: [
  { title: "Shut Up and Drive – Rihanna", file: "mp3/mp3/shut_up_and_drive.mp3" },
  { title: "Blinding Lights – The Weeknd", file: "mp3/mp3/blinding_lights.mp3" },
  { title: "Mr. Brightside – The Killers", file: "mp3/mp3/mr_brightside.mp3" },
  { title: "I Wanna Dance With Somebody – Whitney Houston", file: "mp3/mp3/i_wanna_dance_with_somebody.mp3" },
  { title: "Cake by the Ocean – DNCE", file: "mp3/mp3/cake_by_the_ocean.mp3" },
  { title: "Africa – Toto", file: "mp3/mp3/africa.mp3" },
  { title: "Don’t Stop Believin’ – Journey", file: "mp3/mp3/dont_stop_believin.mp3" },
  { title: "Summer – Calvin Harris", file: "mp3/mp3/summer.mp3" },
  { title: "Hey Ya! – Outkast", file: "mp3/mp3/hey_ya.mp3" },
  { title: "Island in the Sun – Weezer", file: "mp3/mp3/island_in_the_sun.mp3" },
  { title: "Good 4 U – Olivia Rodrigo", file: "mp3/mp3/good_4_u.mp3" },
  { title: "Heat Waves – Glass Animals", file: "mp3/mp3/heat_waves.mp3" },
  { title: "Adore You – Harry Styles", file: "mp3/mp3/adore_you.mp3" },
  { title: "Happy – Pharrell Williams", file: "mp3/mp3/happy.mp3" },
  { title: "Viva La Vida – Coldplay", file: "mp3/mp3/viva_la_vida.mp3" }
],
study: [
  { title: "Sunflower (Instrumental) – Post Malone", file: "mp3/mp3/sunflower.mp3" },
  { title: "Weightless – Marconi Union", file: "mp3/mp3/weightless.mp3" },
  { title: "Cold Little Heart – Michael Kiwanuka", file: "mp3/mp3/cold_little_heart.mp3" },
  { title: "Coffee – beabadoobee", file: "mp3/mp3/coffee.mp3" },
  { title: "Lovely (Instrumental) – Billie Eilish & Khalid", file: "mp3/mp3/lovely.mp3" },
  { title: "Lovely Day (Lofi Remix) – Bill Withers", file: "mp3/mp3/lovely_day.mp3" },
  { title: "Holocene – Bon Iver", file: "mp3/mp3/holocene.mp3" },
  { title: "Lost in Japan (Acoustic) – Shawn Mendes", file: "mp3/mp3/lost_in_japan.mp3" },
  { title: "Bloom – Troye Sivan", file: "mp3/mp3/bloom.mp3" },
  { title: "Ocean Eyes (Acoustic) – Billie Eilish", file: "mp3/mp3/ocean_eyes.mp3" },
  { title: "Pink + White – Frank Ocean", file: "mp3/mp3/pink_+_white.mp3" },
  { title: "Ribs – Lorde", file: "mp3/mp3/ribs.mp3" },
  { title: "Circles (Acoustic) – Post Malone", file: "mp3/mp3/circles.mp3" },
  { title: "Talk – Khalid", file: "mp3/mp3/talk.mp3" },
  { title: "Slow Dancing in the Dark – Joji", file: "mp3/mp3/slow_dancing_in_the_dark.mp3" }
],

coding: [
  { title: "Midnight City – M83", file: "mp3/mp3/midnight_city.mp3" },
  { title: "Sunset Lover – Petit Biscuit", file: "mp3/mp3/sunset_lover.mp3" },
  { title: "Shelter – Porter Robinson & Madeon", file: "mp3/mp3/shelter.mp3" },
  { title: "Lofi Hip Hop", file: "mp3/mp3/lofi_hip_hop.mp3" },
  { title: "Alive – Empire of the Sun", file: "mp3/mp3/alive.mp3" },
  { title: "Strobe – deadmau5", file: "mp3/mp3/strobe.mp3" },
  { title: "Harder, Better, Faster, Stronger – Daft Punk", file: "mp3/mp3/harder_better_faster_stronger.mp3" },
  { title: "Everything Goes On – Porter Robinson", file: "mp3/mp3/everything_goes_on.mp3" },
  { title: "Goodbye to a World – Porter Robinson", file: "mp3/mp3/goodbye_to_a_world.mp3" },
  { title: "Spirals – Jai Wolf", file: "mp3/mp3/spirals.mp3" },
  { title: "Indian Summer – Jai Wolf", file: "mp3/mp3/indian_summer.mp3" },
  { title: "Intro – The xx", file: "mp3/mp3/intro.mp3" },
  { title: "The Less I Know the Better – Tame Impala", file: "mp3/mp3/the_less_i_know_the_better.mp3" },
  { title: "Paper Planes – M.I.A.", file: "mp3/mp3/paper_planes.mp3" },
  { title: "A Moment Apart – ODESZA", file: "mp3/mp3/a_moment_apart.mp3" }
],
commute: [
  { title: "Good Days – SZA", file: "mp3/mp3/good_days.mp3" },
  { title: "Sunflower – Post Malone & Swae Lee", file: "mp3/mp3/sunflower.mp3" },
  { title: "As It Was – Harry Styles", file: "mp3/mp3/as_it_was.mp3" },
  { title: "Peaches – Justin Bieber", file: "mp3/mp3/peaches.mp3" },
  { title: "Bad Habit – Steve Lacy", file: "mp3/mp3/bad_habit.mp3" },
  { title: "Daylight – David Kushner", file: "mp3/mp3/daylight.mp3" },
  { title: "Someone You Loved – Lewis Capaldi", file: "mp3/mp3/someone_you_loved.mp3" },
  { title: "Memories – Maroon 5", file: "mp3/mp3/memories.mp3" },
  { title: "Golden – Harry Styles", file: "mp3/mp3/golden.mp3" },
  { title: "Stay – The Kid LAROI & Justin Bieber", file: "mp3/mp3/stay.mp3" },
  { title: "Lovely – Billie Eilish", file: "mp3/mp3/lovely.mp3" },
  { title: "Supercut – Lorde", file: "mp3/mp3/supercut.mp3" },
  { title: "Sweater Weather – The Neighbourhood", file: "mp3/mp3/sweater_weather.mp3" },
  { title: "Unholy – Sam Smith", file: "mp3/mp3/unholy.mp3" },
  { title: "Heat Waves – Glass Animals", file: "mp3/mp3/heat_waves.mp3" }
],
sleep: [
  { title: "Moon River – Frank Ocean", file: "mp3/mp3/moon_river.mp3" },
  { title: "All I Want – Kodaline (Acoustic)", file: "mp3/mp3/all_i_want.mp3" },
  { title: "Fix You – Coldplay", file: "mp3/mp3/fix_you.mp3" },
  { title: "I Will Follow You Into the Dark – Death Cab for Cutie", file: "mp3/mp3/i_will_follow_you.mp3" },
  { title: "Holocene – Bon Iver", file: "mp3/mp3/holocene.mp3" },
  { title: "Liability – Lorde", file: "mp3/mp3/liability.mp3" },
  { title: "Falling – Harry Styles", file: "mp3/mp3/falling.mp3" },
  { title: "Lovely – Billie Eilish (Acoustic / Piano Cover)", file: "mp3/mp3/lovely.mp3" },
  { title: "The Night We Met – Lord Huron", file: "mp3/mp3/the_night_we_met.mp3" },
  { title: "Bloom – Troye Sivan (Acoustic)", file: "mp3/mp3/bloom.mp3" },
  { title: "Snowfall – Øneheart", file: "mp3/mp3/snowfall.mp3" },
  { title: "idontwanttobeyouanymore – Billie Eilish", file: "mp3/mp3/i_dont_want_to_be_you_anymore.mp3" },
  { title: "Lost – Frank Ocean", file: "mp3/mp3/lost.mp3" },
  { title: "Beyond – Leon Bridges", file: "mp3/mp3/beyond.mp3" },
  { title: "I Get to Love You – Ruelle", file: "mp3/mp3/i_get_to_love_you.mp3" }
],



};
